export const profile = {
  name: 'Sammy Bolger',
  title: 'Enterprise Solution Architecture Analyst',
  company: 'Entegris',
  location: 'Apple Valley, MN',
  school: 'Concordia College, Moorhead',
  tagline:
    'I work across AI engineering, data science, and data engineering. I care about building software that people actually use.',
  bio: `I graduated from Concordia College Moorhead in May 2026 with a B.S. in data science and minors in math and cybersecurity. I'm from Apple Valley, MN.

I'm currently at Entegris on the enterprise architecture team. I built an internal RAG application that cut architecture pattern drafting from about two weeks to under a minute, and I've automated a handful of manual workflows to save the team a significant amount of time.

I'm interested in AI engineering, data engineering, and data science, from RAG systems and agentic AI to data pipelines and machine learning. Most of what I build ends up on my GitHub, open source and updated most days.`,
  socials: {
    email: 'mailto:sammy.bolger@outlook.com',
    github: 'https://github.com/SammyBolger',
    linkedin: 'https://www.linkedin.com/in/sambolger/',
  },
};

export type EducationEntry = {
  school: string;
  location: string;
  degree: string;
  graduation: string;
  minors?: string;
  activities?: string;
};

export const education: EducationEntry[] = [
  {
    school: 'Concordia College',
    location: 'Moorhead, MN',
    degree: 'B.S. Data Science',
    minors: 'Mathematics, Cybersecurity',
    graduation: 'May 2026',
    activities: "Dean's List, Data Science Club, Men's Basketball",
  },
  {
    school: 'Eastview High School',
    location: 'Apple Valley, MN',
    degree: 'Standard Diploma',
    graduation: 'June 2022',
    activities: 'Honor Roll, Varsity Basketball',
  },
];

export const skills: { group: string; items: string[] }[] = [
  {
    group: 'Languages',
    items: ['Python', 'SQL', 'TypeScript', 'JavaScript', 'Java', 'R', 'HTML/CSS'],
  },
  {
    group: 'AI & LLMs',
    items: [
      'LangGraph',
      'LangChain',
      'RAG',
      'Agentic AI',
      'MCP',
      'Prompt Engineering',
      'Claude',
      'OpenAI',
      'Vector Databases',
    ],
  },
  {
    group: 'Libraries & Frameworks',
    items: [
      'FastAPI',
      'dbt',
      'React',
      'Chroma',
      'TensorFlow',
      'XGBoost',
      'MLflow',
      'Streamlit',
      'scikit-learn',
      'Pandas',
      'NumPy',
      'TOGAF',
    ],
  },
  {
    group: 'Cloud & Tools',
    items: [
      'GCP',
      'Vertex AI',
      'Azure',
      'AWS',
      'Docker',
      'GitHub Actions',
      'Supabase',
      'DuckDB',
      'PostgreSQL',
    ],
  },
];

export type Project = {
  name: string;
  role: string;
  summary: string;
  bullets: string[];
  stack: string[];
  links?: { label: string; href: string }[];
  status?: string;
};

export const projects: Project[] = [
  {
    name: 'Bat Echolocation Detection',
    role: 'Concordia College Data Science Lab',
    summary:
      'Classifies bat species from ultrasonic recordings using MobileNetV2 on spectrograms.',
    bullets: [
      'Processed 33,000+ ultrasonic audio files into spectrograms for bat-call classification.',
      'Trained a MobileNetV2 model with transfer learning, achieving 94.6% recall on bat calls.',
      'Validated with confusion matrix, per-class metrics, and cross-validation.',
      'Deployed an interactive app for real-time inference on uploaded audio.',
    ],
    stack: ['Python', 'TensorFlow', 'MobileNetV2', 'librosa'],
    links: [
      {
        label: 'GitHub',
        href: 'https://github.com/SammyBolger/Bat-Detection-Using-Machine-Learning',
      },
    ],
  },
  {
    name: 'PR Reviewer Agent',
    role: 'Personal project',
    summary:
      'Agentic GitHub App that leaves an automatic code review on every pull request within 20 seconds.',
    bullets: [
      'LangGraph state machine: fetch diff, retrieve RAG context, review with Claude, post comment.',
      'Signal-derived confidence from citation validity, RAG hits, and model self-report.',
      'LLM-as-judge eval harness, prompt A/B testing, MCP server, and 66 pytest cases in CI.',
      'Deployed on Fly.io with a hard Anthropic token cap to keep usage predictable.',
    ],
    stack: ['Python', 'FastAPI', 'LangGraph', 'Anthropic Claude', 'Chroma', 'MCP', 'Fly.io'],
    links: [
      { label: 'Live', href: 'https://pr-reviewer-agent.fly.dev' },
      { label: 'GitHub', href: 'https://github.com/SammyBolger/pr-reviewer-agent' },
    ],
  },
  {
    name: 'Tech Brief',
    role: 'Personal project',
    summary:
      'Daily TL;DR of tech news, generated by an LLM agent and delivered to my inbox every morning.',
    bullets: [
      'Daily ELT pipeline ingesting HackerNews, Reddit, RSS, GitHub trending, and ArXiv into DuckDB.',
      'dbt medallion with source and schema tests, scoring stories by weight, recency, and engagement.',
      'LangGraph agent calls Claude Haiku with a Pydantic tool schema for structured summaries.',
      'Runs on GitHub Actions cron and delivers via Resend, all on free tier.',
    ],
    stack: ['Python', 'dbt', 'DuckDB', 'LangGraph', 'Anthropic Claude', 'GitHub Actions', 'Resend'],
    links: [{ label: 'GitHub', href: 'https://github.com/SammyBolger/tech-brief' }],
  },
];

export const experience = [
  {
    org: 'Entegris',
    role: 'Enterprise Solution Architecture Analyst',
    period: 'May 2026 – Present',
    location: 'Chaska, MN',
    bullets: [
      'Built and deployed a full-stack RAG web app in Python, FastAPI, React, and Vertex AI on GCP.',
      'Cut pattern drafting time from two weeks to a minute using BM25 retrieval over 500+ docs.',
      'Built an LLM eval harness measuring retrieval hit rate, faithfulness, and hallucination rate.',
      'Automated a manual application-ID entry workflow with GitHub Actions, saving weekly hours.',
      'Partnered with cross-functional teams to drive architectural decisions and meet business goals.',
    ],
  },
  {
    org: 'Concordia College Data Science Lab',
    role: 'Data Science Associate',
    period: 'Jan 2025 – May 2025',
    location: 'Moorhead, MN',
    bullets: [
      'Trained a k-means ML model on 12,000+ cafe transactions to surface customer buying patterns.',
      'Built a Streamlit demand-forecasting dashboard that informed staffing and cut inventory waste.',
      'Presented findings to non-technical stakeholders across cafe and finance teams.',
    ],
  },
  {
    org: 'City of Apple Valley',
    role: 'Parks Maintenance',
    period: 'Summers, 2022 – 2025',
    location: 'Apple Valley, MN',
    bullets: [
      'Maintained city parks and athletic fields while training seasonal staff on equipment and safety.',
      'Consistently completed daily routes ahead of schedule and mentored new hires over four summers.',
    ],
  },
];
